package com.example.relationshipagent.memory.controller;

import com.example.relationshipagent.common.dto.ApiResponse;
import com.example.relationshipagent.memory.model.MemoryAggregationBatch;
import com.example.relationshipagent.memory.model.MemoryObservation;
import com.example.relationshipagent.memory.service.MemoryAggregationBatchService;
import com.example.relationshipagent.memory.service.MemoryAggregationCandidateService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.http.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import static org.assertj.core.api.Assertions.assertThat;

/** Stage-4 HTTP contract: mutations are scoped before state changes and draft activation stays explicit. */
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT)
@Testcontainers @ActiveProfiles("test")
class MemoryPersonaControllerIT {
    @Container static PostgreSQLContainer<?> postgres=new PostgreSQLContainer<>("pgvector/pgvector:pg17").withDatabaseName("memory_persona_controller_test").withUsername("postgres").withPassword("postgres");
    @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("spring.datasource.url",postgres::getJdbcUrl);r.add("spring.datasource.username",postgres::getUsername);r.add("spring.datasource.password",postgres::getPassword);r.add("spring.flyway.url",postgres::getJdbcUrl);r.add("spring.flyway.user",postgres::getUsername);r.add("spring.flyway.password",postgres::getPassword);r.add("spring.ai.openai.embedding.enabled",()->"false");r.add("ra.memory.enabled",()->"false");}
    @LocalServerPort int port; @Autowired TestRestTemplate http; @Autowired JdbcTemplate jdbc; @Autowired MemoryAggregationBatchService aggregationBatches;
    private String chatFileId,memoryId,profileId;
    @BeforeEach void setup(){jdbc.update("DELETE FROM chat_file");chatFileId=UUID.randomUUID().toString();memoryId=UUID.randomUUID().toString();profileId=UUID.randomUUID().toString();jdbc.update("INSERT INTO chat_file(id,file_name,source_sha256,source_format,file_path,encoding,source_timezone,parser_version,status) VALUES (?,?,?,?,?,?,?,?,?)",chatFileId,"a.csv","sha","CSV","/tmp/a.csv","UTF-8","Asia/Shanghai","v1","READY");jdbc.update("INSERT INTO memory_item(id,chat_file_id,target_person,memory_type,content,status,created_at,updated_at,review_status,memory_key) VALUES (?,?,?,?,?,'ACTIVE',NOW(),NOW(),'PENDING_REVIEW',?)",memoryId,chatFileId,"她","FACT","已验证事实","fact-a");jdbc.update("INSERT INTO persona_profile(id,chat_file_id,target_person,version,profile_json,status,created_at,updated_at) VALUES (?,?,?,?,?,'DRAFT',NOW(),NOW())",profileId,chatFileId,"她","draft-1","{}");}
    @Test void shouldRejectCrossFileMemoryMutationBeforeChangingState(){String wrong="http://localhost:"+port+"/api/chat-files/"+UUID.randomUUID()+"/memories/"+memoryId+"/approve";ResponseEntity<ApiResponse<Map>> response=http.exchange(wrong,HttpMethod.POST,null,new ParameterizedTypeReference<>(){});assertThat(response.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);assertThat(jdbc.queryForObject("SELECT review_status FROM memory_item WHERE id=?",String.class,memoryId)).isEqualTo("PENDING_REVIEW");ResponseEntity<ApiResponse<Map>> ok=http.exchange(memoryUrl("/"+memoryId+"/approve"),HttpMethod.POST,null,new ParameterizedTypeReference<>(){});assertThat(ok.getStatusCode()).isEqualTo(HttpStatus.OK);assertThat(jdbc.queryForObject("SELECT review_status FROM memory_item WHERE id=?",String.class,memoryId)).isEqualTo("APPROVED");}
    @Test void shouldActivateOnlyViaCorrectChatFilePath(){String wrong="http://localhost:"+port+"/api/chat-files/"+UUID.randomUUID()+"/personas/"+profileId+"/activate";ResponseEntity<ApiResponse<Map>> response=http.exchange(wrong,HttpMethod.POST,null,new ParameterizedTypeReference<>(){});assertThat(response.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);assertThat(jdbc.queryForObject("SELECT status FROM persona_profile WHERE id=?",String.class,profileId)).isEqualTo("DRAFT");ResponseEntity<ApiResponse<Map>> ok=http.exchange(personaUrl("/"+profileId+"/activate"),HttpMethod.POST,null,new ParameterizedTypeReference<>(){});assertThat(ok.getStatusCode()).isEqualTo(HttpStatus.OK);assertThat(jdbc.queryForObject("SELECT status FROM persona_profile WHERE id=?",String.class,profileId)).isEqualTo("ACTIVE");}
    @Test void shouldKeepVectorCandidatesReadOnlyAndCrossKey(){String other=UUID.randomUUID().toString();jdbc.update("INSERT INTO memory_item(id,chat_file_id,target_person,memory_type,content,status,created_at,updated_at,review_status,memory_key,embedding,embedding_model) VALUES (?,?,?,?,?,'ACTIVE',NOW(),NOW(),'PENDING_REVIEW',?,CAST(array_fill(0.01::real, ARRAY[1024]) AS vector),?)",other,chatFileId,"她","FACT","等价事实","fact-b","text-embedding-v4");jdbc.update("UPDATE memory_item SET embedding=CAST(array_fill(0.02::real, ARRAY[1024]) AS vector),embedding_model=? WHERE id=?","text-embedding-v4",memoryId);ResponseEntity<ApiResponse<List<Map<String,Object>>>> response=http.exchange(memoryUrl("/"+memoryId+"/similar-candidates?size=5"),HttpMethod.GET,null,new ParameterizedTypeReference<>(){});assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);assertThat(response.getBody().data()).hasSize(1);assertThat(jdbc.queryForObject("SELECT count(*) FROM memory_item WHERE chat_file_id=? AND status='ACTIVE'",Integer.class,chatFileId)).isEqualTo(2);}
    @Test void shouldValidateHumanEditBeforeCreatingNewDraft(){jdbc.update("UPDATE memory_item SET review_status='APPROVED' WHERE id=?",memoryId);String wrong="http://localhost:"+port+"/api/chat-files/"+UUID.randomUUID()+"/personas/"+profileId+"/edits";Map<String,Object> bad=Map.of("draft",Map.of("schemaVersion","persona-profile-v1","communicationStyle",Map.of("statement","她表达直接","sourceMemoryIds",List.of(memoryId)),"preferences",List.of(),"dislikes",List.of(),"interactionPatterns",List.of(),"emotionalExpression",List.of(),"values",List.of(),"boundaries",List.of(),"fewShotExamples",List.of(),"limitations",List.of()));ResponseEntity<ApiResponse<Map>> rejected=http.exchange(wrong,HttpMethod.POST,new HttpEntity<>(bad),new ParameterizedTypeReference<>(){});assertThat(rejected.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);assertThat(jdbc.queryForObject("SELECT count(*) FROM persona_profile WHERE chat_file_id=?",Integer.class,chatFileId)).isEqualTo(1);ResponseEntity<ApiResponse<Map>> created=http.exchange(personaUrl("/"+profileId+"/edits"),HttpMethod.POST,new HttpEntity<>(bad),new ParameterizedTypeReference<>(){});assertThat(created.getStatusCode()).isEqualTo(HttpStatus.OK);assertThat(jdbc.queryForObject("SELECT count(*) FROM persona_profile WHERE chat_file_id=? AND change_type='HUMAN_EDIT' AND status='DRAFT'",Integer.class,chatFileId)).isEqualTo(1);}
    @Test void shouldRequeueInterruptedAggregationAndRejectOldLeaseCompletion(){MemoryObservation observation=new MemoryObservation();observation.setId(UUID.randomUUID().toString());MemoryAggregationCandidateService.Candidate candidate=new MemoryAggregationCandidateService.Candidate("event-a","EVENT","NEUTRAL",List.of(observation));String inputHash="a".repeat(64),firstLease=UUID.randomUUID().toString(),secondLease=UUID.randomUUID().toString();MemoryAggregationBatch interrupted=aggregationBatches.claim(chatFileId,"她",inputHash,candidate,firstLease);assertThat(interrupted).isNotNull();aggregationBatches.requeueRunning(chatFileId,"她",inputHash);MemoryAggregationBatch resumed=aggregationBatches.claim(chatFileId,"她",inputHash,candidate,secondLease);assertThat(resumed).isNotNull();assertThat(resumed.getId()).isEqualTo(interrupted.getId());aggregationBatches.success(interrupted.getId(),firstLease,null,1);assertThat(jdbc.queryForObject("SELECT status FROM memory_aggregation_batch WHERE id=?",String.class,interrupted.getId())).isEqualTo("RUNNING");aggregationBatches.success(resumed.getId(),secondLease,null,1);assertThat(jdbc.queryForObject("SELECT status FROM memory_aggregation_batch WHERE id=?",String.class,resumed.getId())).isEqualTo("SUCCESS");assertThat(aggregationBatches.claim(chatFileId,"她",inputHash,candidate,UUID.randomUUID().toString())).isNull();}
    private String memoryUrl(String suffix){return "http://localhost:"+port+"/api/chat-files/"+chatFileId+"/memories"+suffix;}
    private String personaUrl(String suffix){return "http://localhost:"+port+"/api/chat-files/"+chatFileId+"/personas"+suffix;}
}
