package com.example.relationshipagent.analysis.model;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * Event candidate generated by deterministic rules or human review.
 */
@Data
@TableName("relationship_event")
public class RelationshipEvent {
    @TableId(type = IdType.INPUT)
    private String id;
    private String chatFileId;
    private String eventType;
    private Instant startTime;
    private Instant endTime;
    private String statement;
    private String evidence;
    private String counterEvidence;
    private BigDecimal confidence;
    private String source;
    private String reviewStatus;
    private Instant createdAt;
    private String eventKey;
    private String detectorVersion;
    private String inputHash;
    private String metricsJson;
    private Instant updatedAt;
}
